### ISSUE TITLE
receive updating/updated relationship

### ISSUE THREAD

**Issue by martintern** [fico7489/LaravelPivot#2]
Is there a way to know which relationship was updated?
Like
```php
static::updated(function ($user, $relationship) {
```

**Comment by fico7489** [comment]
no, because I just hooked updates on BelongsToManyCustom relation to laravel standard events updating and  updated. 
Information about which relationship was updated does not make sense on updating and updated events. For this kind information is necessary to create new event, e.g. "pivotUpdated", "belongsToManyUpdated" or something like that and pass that kind of information there...

```
static::pivotUpdated(function ($user, $relationship) {
   ...
})
```

**Comment by fico7489** [comment]
new package version is pushed now you can know which relation and which ids, check readme..
