### ISSUE TITLE
Events in pivot model, not in regular model

### ISSUE THREAD

**Issue by anurbol** [fico7489/LaravelPivot#28]
Very nice package! Thanks! 

Unfortunately totally have no time for making a pull request, but it would be nice to have events in **pivot models** like this:

    class UserRole extends Pivot
    {
        public static function boot()
        {
             self::creating(...
             self::retrieved(...

and all other standard events: https://laravel.com/docs/5.6/eloquent#events

I think it would be really cool, in respect of separation of concerns, and will make related models cleaner.

P.S. About pivot models: https://laravel.com/docs/5.6/eloquent-relationships#many-to-many ("Defining Custom Intermediate Table Models" section)

**Comment by fico7489** [comment]
I don't think that is a good idea, because when you call attach () laravel perform raw bulk query without a model.  To do what you said I would need to change this code which is doing that and in foreach loop update each pivot model. This package is just about firing events I don't want to change thinks how laravel is attaching pivots...Another soulution would be to get all pivot models separately base on $pivotIdsAttributes and in foreach loop fire events for each model. I think that that soulution even less makes sense

**Comment by anurbol** [comment]
Well thanks for reply! I understand you. Let's just keep this issue open for a while, maybe 1-2 months, who knows, maybe someone can offer something valuable to this... If not, then let's close the issue :) Because you know, your package is most popular among similar ones, so some discussion here would not harm, i think

**Comment by fico7489** [comment]
Actually the reason why this package exists is that laravel is not using pivot models for attach(), sync() and update() methods. We can create a new package that would do this, but in that case we don't need any new events and all current code from this package is unnecessary, because  in that case we just can listen standard eloquent events(update, create, delete) on that pivot model. But the problem is that using models can slow things significantly...
