### ISSUE TITLE
Only fire pivotUpdated if real change was made.

### ISSUE THREAD

**Issue by bleamb** [fico7489/LaravelPivot#39]
The default eloquent updated method will not fire if you 'update' a model with the same details. Calling sync() seems to fire pivotUpdated even if what you pass into sync() is the same as what's already in the pivot table

**Comment by GregorBeatson** [comment]
I seem to have been able to fix this with a really simple change in FiresPivotEventsTrait.php:

```
    public function updateExistingPivot($id, array $attributes, $touch = true)
    {
        list($idsOnly, $idsAttributes) = $this->getIdsWithAttributes($id, $attributes);

        $this->parent->fireModelEvent('pivotUpdating', true, $this->getRelationName(), $idsOnly, $idsAttributes);
        $parentResult = parent::updateExistingPivot($id, $attributes, $touch);
        if ($parentResult) { // here
            $this->parent->fireModelEvent('pivotUpdated', false, $this->getRelationName(), $idsOnly, $idsAttributes);
        } // here

        return $parentResult;
    }
```

**Comment by fico7489** [comment]
thanks for contribution, I will check this soon...

**Comment by fico7489** [comment]
I tested laravel behaviour, I put this in model : 

    public static function boot()
    {
        parent::boot();

        static::saving(function ($model) {
            echo 'saving';
        });

        static::saved(function ($model) {
            echo 'saved';
        });
    }

1.with this code : 

    $product = \App\Models\Product::find(1);
    $product->update([]);

output is : 

    saving
    saved

updated_at field is NOT CHANGED

2.with this code : 

    $product = \App\Models\Product::find(1);
    $product->update(['name' => str_random(150)]);

output is : 

    saving
    saved

updated_at field is CHANGED

**Comment by fico7489** [comment]
I investigated this problem and conclusion is that I can't detect if same data is passed in sync() because  laravel does not use pivot model class for updates action on pivot table. Laravel use model class for normal updates and that is the reason why you can detect if anything changed easily inside model.

For pivot update actions laravel use raw queries directly on database without pivot models and that is actually the reason why this package exists. If laravel would use models for pivot action you could use just this : 

    public static function boot()
    {
        parent::boot();

        static::saving(function ($model) {
            echo 'saving';
        });

        static::saved(function ($model) {
            echo 'saved';
        });
    }

inside Illuminate\Database\Eloquent\Relations\Pivot class and you would not need this package.
