### ISSUE TITLE
nice.

### ISSUE THREAD

**Issue by fgutteridge** [fico7489/LaravelPivot#61]
Followed the docs, and nothing seems to work.

**Comment by janicerar** [comment]
Same issue here.

**Comment by joeelia** [comment]
@fgutteridge

You are on Github, let me teach you that's a place where people share some code to the community even if it's not perfect. Do you know why ? Because you can help people by sharing your "big" knowledge. And because you seem to be a "great" developer, why not making a pull request ? No... you prefer to insult people like the dumbass you are...

Also the package works fine for me.

**Comment by fico7489** [comment]
@fgutteridge @janicerar  the package are working for more than 250 people as you can see. Can you describe what are you doing, paste some of your code and tell which laravel version are you using ?

**Comment by panuci** [comment]
@fgutteridge @janicerar The package is working fine for me. The documentation may be a little off in the part of calling static methods direclty inside the model class. In order to catch those events you have to call those methods inside the boot function in your model class.

If this doesn't help, please, give us further information what is the problem or error message you are facing

**Comment by sonalmahajan01** [comment]
I am facing the same issue. I did a composer install. 
I have a user table, departments, department_users (pivot table).

User Model :
`use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;
use Illuminate\Database\Eloquent\Model;

class User extends Authenticatable implements Auditable
{
    use PivotEventTrait; //trigger events when pivot tables are attached

    public function departments() {
        return $this->belongsToMany(Department::class, 'department_users');
    }
    public static function boot() {
        parent::boot();
        //Log::info('boot called');
        static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            Log::info( 'pivotAttached');
            Log::info(get_class($model));
            Log::info($relationName);
            Log::info(json_encode($pivotIds));
            Log::info(json_encode($pivotIdsAttributes));
        });
   }
`
I am attaching and detaching using Laravel Nova. (Can that be potential issue? But they also call attach and detach on the base model). 
Update: I tried the same from code but again, no event triggered. I am on laravl 5.8

**Comment by ChrisHelmsC** [comment]
I tried this on User and was unable to get the events to trigger. I then moved it to the other model in the many to many relation (event in my case) and it worked correctly. Maybe this issue is related to extending Authenticatable instead of directly extending model?

**Comment by fico7489** [comment]
I can see that each you case is different can everyone open a separate issue with some extensive explanation and code example...thanks....

**Comment by fgutteridge** [comment]
lmao @ all the people now taking issue
