### ISSUE TITLE
Issue w/ Laravel Nova

### ISSUE THREAD

**Issue by Aontaigh** [fico7489/LaravelPivot#62]
I have the package working correctly when it comes to doing things when hitting controllers via axios requests.

As a test in an index method of a controller this line of code exists: 

`$campaign->sites()->attach(Site::find(1));`

This successfully hits these two methods located in the boot function of the campaign model:

```
static::pivotAttaching(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
    dump('pivotAttaching');
});

static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
    dump('pivotAttached');
});
```

Though these methods are not hit when using Nova.

In Campaign.php for Nova there is this line located in the fields method:

`BelongsToMany::make('Sites')`

This is not hitting pivotAttaching or pivotAttached.

**Comment by sicbe** [comment]
I'm trying to do the same thing. I read somewhere some time ago that Nova doesn't use the "attach" and "detach" functions to save the relationships; which is why these events aren't fired. Haven't found a solution to it yet.

**Comment by tomscholz** [comment]
The solution is to use custom Pivot models that will fire the events provided by this library manually. To be honest, I don't know if it really works with this library, since I'm using [Eventually](https://altek.gitlab.io/eventually/), but it's the same concept.

Here's an example how that could look like:

You'll need to create new pivot models for each relation where you use nova.
```php
<?php
namespace App\Pivots;

use Illuminate\Database\Eloquent\Relations\Pivot;


abstract class Pivot extends EloquentPivot
{
    /**
     * @var string
     */
    public $relationName;

    /**
     * {@inheritDoc}
     */
    public static function boot()
    {
        parent::boot();

        static::saving(function ($model) {
            $model->pivotParent->firePivotEvent('attaching', true, $model->relationName, [$model->attributes]);
        });

        static::saved(function ($model) {
            $model->pivotParent->firePivotEvent('attached', true, $model->relationName, [$model->attributes]);
        });

        static::deleting(function ($model) {
            $model->pivotParent->firePivotEvent('detaching', true, $model->relationName, [$model->attributes]);
        });

        static::deleted(function ($model) {
            $model->pivotParent->firePivotEvent('detached', true, $model->relationName, [$model->attributes]);
        });

        static::updating(function ($model) {
            $model->pivotParent->firePivotEvent('updatingExistingPivot', true, $model->relationName, [$model->attributes]);
        });

        static::updated(function ($model) {
            $model->pivotParent->firePivotEvent('existingPivotUpdated', true, $model->relationName, [$model->attributes]);
        });
    }
}

// In an extra file extend the Pivot class and add the name of the relation 
class UserLicenses extends Pivot
{
    public $relationName = 'licenses';
}
```

Then in your model you have to tell the relation to use the pivot model.
```php
class User extends Model
{
    /**
     * The licenses of the casino operator.
     */
    public function licenses()
    {
        return $this->belongsToMany('App\License')->using(UserLicenses::class);
    }
}
```

When using Morphs), you'll have to create a new abstract Pivot class that extends MorphPivot instead of `Pivot`.

The above works, because `Pivot` extends `Model` and therefor has the same events. Except for `retrieved` and some other, but I don't remember them right now.

**Keep in mind that if you access the relation not using nova, it will fire the events twice.**

I know I'm late to the party, but maybe it helps.

Cheers.

**Comment by BKorenek** [comment]
The exception does go away whenever I update 

vendor/fico7489/laravel-pivot/src/Traits/ExtendFireModelEventTrait.php:34
to
`$payload = [0 => $this, 'relation' => $relationName, 'pivotIds' => $ids, 'pivotIdsAttributes' => $idsAttributes];`

**Comment by fico7489** [comment]
closing because it is outdated
